<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CredentialManagement" Version="1.0.2" />
	</ItemGroup>
	<ItemGroup>
		<COMReference Include="MSTSCLib">
			<Guid>8C11EFA1-92C3-11D1-BC1E-00C04FA31489</Guid>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<WrapperTool>tlbimp</WrapperTool>
			<EmbedInteropTypes>true</EmbedInteropTypes>
		</COMReference>
		<COMReference Include="AxMSTSCLib">
			<Guid>8C11EFA1-92C3-11D1-BC1E-00C04FA31489</Guid>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<WrapperTool>aximp</WrapperTool>
		</COMReference>
	</ItemGroup>
</Project>
